# Generated by Django 4.1.7 on 2023-03-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, verbose_name='Наименование')),
                ('picture', models.ImageField(upload_to='pictures', verbose_name='Изображение награды')),
                ('description', models.TextField(verbose_name='Описание награды')),
                ('conditions', models.TextField(verbose_name='Условия получения награды')),
                ('necessary_awards', models.TextField(verbose_name='Необходимые награды')),
                ('excluding_awards', models.TextField(verbose_name='Запрещающие награды')),
                ('entry', models.FileField(upload_to='entryes', verbose_name='Заявка на получение награды')),
                ('rank', models.IntegerField(verbose_name='Степень ордена')),
            ],
        ),
    ]
