# Generated by Django 4.1.7 on 2023-03-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='necessary_docs',
            field=models.FileField(blank=True, default=None, null=True, upload_to='docs', verbose_name='Заявка на получение награды'),
        ),
    ]
